[package]
name = "hello"
version = "0.1.0"
authors = ["Konstantin Perikov <pericov.ko@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
num-traits = "0.2"
num = "0.2.1"
image = "0.23.0"
